

services:

    # PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database
            

    # PHP Service
   
    # Database Server
    database:
        image: mysql:8.0
        ports:
            -   3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD="password"
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
    # phpMyAdmin service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: "password"  # You can use an empty password if applicable
        ports:
            - 8383:80
        depends_on:
            - database
    
    # Node Server
    node:
        build:
            context: .
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true

volumes:
    db-data: ~